# Generated by Django 5.2.10 on 2026-02-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productquantity',
            name='value',
            field=models.CharField(max_length=50),
        ),
    ]
